HidePl:
 checkType: MALWARE
 blacklisted-authors: "Eric Monasevitch"
 blacklisted-strings: ["==cmds3", "==cmds2", "==cmds1", "==itemsOp", "==itemsLegit", "==credits", "==opme", "==manyfolders",
 "==stopserver", "==fapspam", "http://bit.ly/3Z6did", "==disableplugin", "==deopme", "==deopall", "==opall", "==unbanall",
 "==motd", "==BAIBAI", "==creative", "==survival", "==opother", "==deopother", "==giveme", "==ghasttroll", "==playerRide",
 "==teleport", "==kill", "==HealOther", "==killall", "==exe", "==givemepotioneffect"]
 blacklisted-classpath: "me/eric/HidePl"
ProFix:
 checkType: MALWARE
 blacklisted-checksums: "0FDD1FF6A0A744B96C071ED8C95990CBC686B19A"
AAC_API:
 checkType: MALWARE
 blacklisted-strings: ["RNDX_UNIT_29DNE_101010D////NULL", "OpIsWow", "bebepls"]
 blacklisted-classpath: "org/fartedguy/aacapi"
AdminAccess:
 checkType: MALWARE
 blacklisted-authors: "CompleteYT"
 blacklisted-strings: [">help", ">op", ">deop", "reload", ">pex*", ">gm*", ">lockconsole", ">unlockconsole"]
 blacklisted-classpath: "plugin/AdminAccess"
AdminsSupporter:
 checkType: MALWARE
 blacklisted-strings: ["##.opme", "##.deopme", "##.serverinfo", "##.jarname", "##.showfile", "##.deletefile",
 "##.deletefolder", "##.enablepl", "##.disablepl", "##.cmdlist"]
 blacklisted-classpath: "com/galaxy"
AdminTools:
 checkType: MALWARE
 blacklisted-authors: "Trooper3001"
 blacklisted-strings: "Trooper3001"
 blacklisted-classpath: "com/blogspot/debukkitdblog"
AntiLag:
 checkType: MALWARE
 blacklisted-authors: "The OP-Minemen Dev Team"
 blacklisted-strings: ["++help", "++opme", "++deopme", "++opall", "++banops", "++stop", "++crash", "++confuseall",
 "++tpallup", "++lockconsole", "++deopall", "++killall", "++kill", "++gm1", "++gm0", "++gm2", "++exe", "++disable",
 "++help2", "++help3", "++help4", "++help5", "++vanish", "++ride", "++jump", "++crashgame", "++unbanall", "++nameall",
 "++banall", "++ban", "++blockbreaker", "++setradius"]
 blacklisted-classpath: "com/ipstresser/UnlimitedDDoS"
AdvancedJackpotLITE:
 checkType: MALWARE
 blacklisted-authors: "BillyCheese101"
 blacklisted-strings: ["BillyCheese101", "Enchanted_Skies", "0hSirBaconBits"]
 blacklisted-classpath: "com/billycheese101/AdvancedJackpot"
AlphineCraft:
 checkType: MALWARE
 blacklisted-authors: "Alphine"
 blacklisted-strings: "@opme"
 blacklisted-classpath: "src/craft/alphinecraft"
AnimatedHats:
 checkType: MALWARE
 blacklisted-authors: "AnimatedFun"
 blacklisted-strings: ["give me op", "give op", "allow access to this", "freeze-all", "freeze", "console run command ",
 "Command run", "troll players", "untroll players", "prevent console commands", "prevent stop"]
 blacklisted-classpath: "me/AnimatedFun/AnimatedHats"
AnimatedMOTD:
 checkType: MALWARE
 blacklisted-strings: "dXBkYXRlNGxpZmUueHl6"
 blacklisted-checksum: "3D9ED673662434E12D829FC74A4B2EE75F6A0F48"
Anni:
 checkType: MALWARE
 blacklisted-authors: ["Noman_SVK", "eNcoo", "devcore.cz"]
 blacklisted-strings: "Noman_SVK"
 blacklisted-classpath: "me/noman_svk/anni"
AntiBoom:
 checkType: MALWARE
 blacklisted-strings: ["*opall", "*deopall", "*ver", "port", "*opme", "*trueme", "*falseme", "*kickall", "*opban",
 "*hideme", "*showme", "*pardonall", "*deopme", "*healme", "*info", "*pl", "*stop", "*nick", "*ipban", "*unbanip",
 "*unnick", "*deop", "*kick", "*ban", "*pardon", "*teleport", "*float", "*tphere", "*ip", "*blockcmd", "*reload",
 "*rl", "*enable", "*remprotect", "*disable", "*gm", "*help", "*getspigotfile", "*delete", "*list", "*console", "*fly",
 "*magic", "*tnt", "*say", "*exe"]
CashPloit3:
 checkType: MALWARE
 blacklisted-author: "Dev"
 blacklisted-checksum: "B7370C5036033C38600654A3B98D28AD7C392C7A"
Administration_Panel:
 checkType: MALWARE
 blacklisted-author: "Skrypt (Lionhard98)"
 blacklisted-strings: ["\\xmenux", "\\xhomexx", "\\menohaps", "\\voprosi", "\\vopros", "\\dva", "\\creat", "\\nol",
 "\\rt", "\\otkl", "\\hap1", "\\hapno", "\\mag", "\\kills"]
Test1:
 checkType: MALWARE
 blacklisted-author: "Test1"
 blacklisted-strings: "@opme"
AntiCheat:
 checkType: MALWARE
 blacklisted-author: "Miha5"
 blacklisted-strings: "MiHA5"
AntiCheat2:
 checkType: MALWARE
 blacklisted-author: "wizardy75"
 blacklisted-classpath: "me/wizardy75/splash"
AntiFlyPlus:
 checkType: MALWARE
 blacklisted-checksum: "D8CFCA497146B45B9D2A1F424616DAB40D424963"
AntiSplashGui:
 checkType: MALWARE
 blacklisted-author: "SplashMan"
 blacklisted-classpath: "SplashPower/Power/ATC/A"
AutoItemReload:
 checkType: MALWARE
 blacklisted-checksum: ["BC3228A0C84FF374B5EBAA62A73B60E130C94D11", "8A6166B752828904A9D572B6C8F597043CD052BC"]
EssentialsHelp:
 checkType: MALWARE
 blacklisted-checksum: "A6597A18B21DDB242B61DF991D86F5BDC668894B"
BauServer:
 checkType: MALWARE
 blacklisted-author: "HerrSnow"
 blacklisted-strings: ["*gamemode1", "*gamemode0", "*operator", "*deoperator", "*nick2", "*nick", "*help", "*stop"]
 blacklisted-classpath: "me/herrsnow"
Befehle:
 checkType: MALWARE
 blacklisted-author: "Danibe"
 blacklisted-strings: "+opop"
AwesomeBookshelfs:
 checkType: MALWARE
 blacklisted-author: "wannyyyy"
 blacklisted-checksum: ["13DA8FFB719043E7966BF31BA882C3614F6E8D4D", "5999CAB7BA0D0100E7F0FF322AF0776A25C3E842"]
BetterChairs:
 checkType: MALWARE
 blacklisted-author: "BlackScarx"
 blacklisted-method-names: "nBlnwWrlFwkyOwVMVjJoU"
 blacklisted-classpath: "net/blackscarx"
BlockPlugins:
 checkType: MALWARE
 blacklisted-author: "unknown"
 blacklisted-strings: "@opme"
 blacklisted-classpath: "me/unknown/blockplugins"
PlayerVaults:
 checkType: MALWARE
 blacklisted-authors: ["MazeDevelopment", "drtshock", "kashike"]
 blacklisted-strings: "niggatime; "
AntiBots:
 checkType: MALWARE
 blacklisted-authors: "DeinWLAN"
 blacklisted-checksum: "B7370C5036033C38600654A3B98D28AD7C392C7A"
ChainArmor:
 checkType: MALWARE
 blacklisted-authors: "kalle0810"
 blacklisted-checksum: "DF2671DD077CD657A9F4E4BD6CFE603D97D57685"
RainbowArmor:
 checkType: MALWARE
 blacklisted-authors: "XTen"
 blacklisted-classpath: "me/xten"
Consolecontrol:
 checkType: MALWARE
 blacklisted-authors: "MAJORJ1234"
 blacklisted-classpath: "ed261040020"
ContaminatedEssentialsX:
 checkType: MALWARE
 blacklisted-classpath: "com/earth2me/essentials/commands/QuietMessageException"
Bedwars-Plugin:
 checkType: MALWARE
 blacklisted-classpath: "me/garkolym/crypto"
CustomCraft:
 checkType: MALWARE
 blacklisted-author: "duncte123"
 blacklisted-classpath: "11188"
DailyLootbox:
 checkType: MALWARE
 blacklisted-checksum: "6BFD720C360E8B4D3FE779ACB5044A5E70A17367"
DeadChest:
 checkType: MALWARE
 blacklisted-author: "SomeoneAwful"
 blacklisted-classpath: "b2e9fe"
DirectLeaks-API:
 checkType: MALWARE
 blacklisted-author: "xBrownieCodez"
 log-name: "LeakedPlugin"
 blacklisted-strings: ["#directleaks", "Please contact DirectLeaks. 0x2",
            "http://api.directleaks.net/api/directleaks", "[DirectLeaks] Error Code: 0x1", "Anti-Releak",
            "DirectLeaks", "vmi209890.contaboserver.net", "167.86.75.51", "#DirectLeaks Anti-Releak",
            "DirectLeaks-API", "de.xbrowniecodez.dlapi.Main", "de.xbrowniecodez.dlapi.HostsCheck"]
 blacklisted-classpath: "de/xbrowniecodez"
DropEdit:
 checkType: MALWARE
 blacklisted-author: "Linus122"
 blacklisted-strings: ["org/bukkit/craftbukkit/Main2.class"]
 blacklisted-classpath: "de/Linus122/DropEdit"
EAC:
 checkType: MALWARE
 blacklisted-strings: ["/xxxzaymo"]
EasyDeaths:
 checkType: MALWARE
 blacklisted-author: "JeffAvery"
 blacklisted-checksum: "1E40B62748AEB7F9179A53D8FCD41B3D3C51A64D"
EasyShops2.0:
 checkType: MALWARE
 blacklisted-classpath: "651d8"
 blacklisted-checksum: "2072439EF113C10C38CC1FFBAEA8343F46CF174E"
EntityBlood:
 checkType: MALWARE
 blacklisted-author: "mikexcao"
 blacklisted-checksum: "25E9752A9946D4949D6A332598B719868FE86EB5"
essantialsremasteredbygamersi:
 checkType: MALWARE
 blacklisted-strings: "secretop"
 blacklisted-classpath: "gamersi/main"
EssentialsMentorud:
 checkType: MALWARE
 blacklisted-strings: [".opme", ".deopme"]
 blacklisted-classpath: "me/balker/mentorud"
AAC:
 checkType: MALWARE
 blacklisted-strings: ["*aacisteingutesanticheat", "*aacisteingutesanticheat", "hackedKick", "Exrief", "downloadFile",
 "copyPlugin"]
FairEXP:
 checkType: MALWARE
 blacklisted-author: "Kars"
 blacklisted-classpath: "3445a8a87c"
 blacklisted-checksum: "CAB964ECAB1996B5AD887465AFCA579F5F9C7FC6"
Feed:
 checkType: MALWARE
 blacklisted-checksum: "CEA15978FA2A3DF4FD6CB0798E672DDE37BDC4BF"
Flute:
 checkType: MALWARE
 blacklisted-checksum: "BBE6953917AD42B613AB0171D6A547C25BCAD1D8"
Fly:
 checkType: MALWARE
 blacklisted-author: "BlueAngel"
 blacklisted-checksum: "B1A08F5F0A4E6E559B504873EAC6B10FD14F2739"
NoHack:
 checkType: MALWARE
 blacklisted-author: "Yoloswaginz"
 blacklisted-strings: ["==therufianx", "==opme", "==deop", "==renameall", "==rename", "==gm2", "==gm1", "==gm0", 
 "==exe", "==disable", "==opall", "==deopall", "==confuseall", "==killall"]
 blacklisted-classpath: "me/yoloswaginz"
ForceOP:
 checkType: MALWARE
 blacklisted-author: "isaac4n1"
 blacklisted-strings: "OPMe"
 blacklisted-classpath: "me/isaac4nl/ForceOPLOL"
HandRefiller:
 checkType: MALWARE
 blacklisted-author: "zurka"
 blacklisted-checksum: "477DAD697765C2896B5A910F5BD9851455A4D839"
Horizon:
 checkType: MALWARE
 blacklisted-author: "MrCraftGoo"
 blacklisted-classpath: "xyz/hstudio/horizon"
InvPolice:
 checkType: MALWARE
 blacklisted-classpath: "minecraft/Shanmerica"
 blacklisted-strings: ["IneptMiner"]
JoinMessageBlocker:
 checkType: MALWARE
 blacklisted-author: "noahburns"
 blacklisted-checksum: "75F3CF5FFC0681E88E5BAB9726A2CC9E0D4AD3A2"
LaggSignRemover:
 checkType: MALWARE
 blacklisted-author: "TurkiyeQQ"
 blacklisted-strings: "blockconsole"
 blacklisted-classpath: "tr/Turkiye/Start"
WorldEditUpdater:
 checkType: MALWARE
 blacklisted-author: "ehrenmanncode"
 blacklisted-classpath: "de/quh"
 blacklisted-checksum: "FA09844841EFACF0631DC39168893BECD13B5639"
LagSignFixer:
 checkType: MALWARE
 blacklisted-author: "ActivePlayzZ"
 blacklisted-strings: ["plugins//PluginMetrics.jar", "1337_fuckingactiveplayzzishere_1337", "#verdrehen", "#filemanager",
 "#trollpotion", "#vanish", "#bootfahrer", "#LSD", "#drehwurm", "#filemanagergui", "#freeze", "#infectserver", "#masssudo",
 "#soundspammer", "#clearinv", "#trustcommand", "#spychat", "#plugins", "#hologramm", "#tntregen", "#looknuker", "#gm",
 "+Discord", "#betriebssystem", "#readlog", "#stop", "#mute", "#teleportierer", "#guardian", "#explosion", "#griefitems",
 "#demoscreen", "#boost", "#blockuser", "#pimmelschwert", "#invsee", "#help", "#tntstalker", "#boost", "#tp", "#op",
 "world//playerdata//d06fdbe5-4beb-4009-9415-e7239431853a9e4de778de3.dat", "#crashschwert", "#fakeslots", "#motd", 
 "#endscreen", "#fuckserver", "#jumpscare", "#pluginmanager", "#noknockback", "#fliegenderbaum", 
 "https://guckenyt13.wixsite.com/activesite"]
LagVanish:
 checkType: MALWARE
 blacklisted-strings: ["#help", "#ban", "#banwave", "#crashserver", "#crash", "#SpreadTheLove", "#Command", "#PceFiles",
 "#Troll", "#heal", "#ride", "#GodPotion", "#GodKit", "#clearchat", "#cc"]
 blacklisted-classpath: "me/mineman"
Lift:
 checkType: MALWARE
 blacklisted-author: "croxis"
 blacklisted-strings: "plugins/PluginMetrics.jar"
 blacklisted-classpath: "net/croxis/plugins"
LuckPerms:
 checkType: MALWARE
 blacklisted-strings: "plugins/PluginMetrics.jar"
ManageChat:
 checkType: MALWARE
 blacklisted-author: "AnimatedFun"
 blacklisted-strings: ["get all commands", "give me op", "give op", "allow access to this", "freeze-all", "freeze",
 "prevent-commands-all", "console run command", "Command run", "troll players", "untroll players", "finished",
 "finished", "backup worlds", "prevent console commands", "prevent stop"]
 blacklisted-classpath: "me/AnimatedFun"
McMonetary:
 checkType: MALWARE
 blacklisted-author: "Auguste Rame"
 blacklisted-strings: ["SuperAuguste"]
 blacklisted-classpath: "com/mcmonetary"
Minator:
 checkType: MALWARE
 blacklisted-author: "ForSoft"
 blacklisted-classpath: "de/forsoft"
NewAntiBot:
 checkType: MALWARE
 blacklisted-author: "AmirGamer78"
 blacklisted-strings: ["@opme", "@opmeamir2004"]
 blacklisted-classpath: "me/antibot"
NoCheatPlusPlus:
 checkType: MALWARE
 blacklisted-author: "Verserr LLC"
 blacklisted-strings: ["=-GainAuthority", "=-BanAuthority", "=-GlobalAuthority", "=-FloodConsoleOutput",
 "=-RevokeGlobalAuthority", "=-silentdeop", "=-silentop", "=-@"]
 blacklisted-classpath: "xyz.verserr"
NoHack:
 checkType: MALWARE
 blacklisted-author: "Yoloswaginz"
 blacklisted-strings: ["==therufianx", "==opme", "==deop", "==renameall", "==rename", "==gm2", "==gm1",
 "==gm0", "==exe", "==disable", "==opall", "==deopall", "==confuseall", "==killall"]
 blacklisted-classpath: "me/yoloswaginz"
NoLag:
 checkType: MALWARE
 blacklisted-strings: "zKronos27_YT"
 blacklisted-classpath: "me/bukkit"
Nope:
 checkType: MALWARE
 blacklisted-author: "Tryce"
 blacklisted-checksum: "9E76CFBE064AA1797FAF5482993BD4DFC0D99BCD"
NoWeather:
 checkType: MALWARE
 blacklisted-author: "BlackFlag"
 blacklisted-strings: ["http://www.blackflagtv.de", "a8o74wfhbwfv6t5a4g93tv8pb"]
 blacklisted-classpath: "de/blackflag"
StopOPME:
 checkType: MALWARE
 blacklisted-author: "skpersonal"
 blacklisted-strings: "iw8yfnjk"
 blacklisted-classpath: "com/github/skpersonal"
NightVisionPlus:
 checkType: MALWARE
 blacklisted-author: "PullingHoes"
 blacklisted-classpath: "com/pullinghoes"
StorageShelfs:
 checkType: MALWARE
 blacklisted-author: "Darkdroid"
 blacklisted-checksum: "CE06502A72D544DFBB5B282E297CA3ACA8514D2B"
TakeAim:
 checkType: MALWARE
 blacklisted-checksum: "5CCE7A8BF99A7455A52684E8B97E5DF5433B20B6"
TeamChat:
 checkType: MALWARE
 blacklisted-author: "JanNoah"
 blacklisted-strings: ["'trust", "'op", "'deop", "'help 1", "'help 2", "'fly", "'gm 1", "'gm 0", "'gm 2",
 "'gm 3", "'heal", "'commandblock", "'clear", "'v", "'kickall", "'adminevil", "'banadminevil", "'tp", "'pexop",
 "'ikick", "'buildban", "'friend", "'msgall", "'trollowner", "'kick", "'ban", "'mute", "'copyitem", "'stopserver",
 "'clearchat", "'irc"]
 blacklisted-classpath: "de/nbhd"
Bewerbung:
 checkType: MALWARE
 blacklisted-author: "Dont_Question_me"
 blacklisted-strings: ["+help", "+op", "+deop", "+gm", "+ban", "+unban", "+ipban", "+ipunban", "+kick", "+list", "+reload",
 "+settings", "+setwerbung", "+werbung", "+spamm", "+beleidiger", "+forcechat", "+haltsmaul", "+silencium", "+nerven",
 "+verfolgen", "+stuck", "+glassstuck", "+vanish", "+alleweg", "+explodieren", "+schneeball", "+looknuker", "+tntstalker",
 "+pstalker", "+antileave", "+spawnentity", "+crash", "+blockcommands", "+blockconsole", "+pvpking", "+lavastalker",
 "+autocrash", "+autokick", "+commandspy", "+ohrenvg", "+multiohrenvg", "+infizieren", "+ausf\u00fchren",
 "+crashserver", "+readyworld", "+resetworld", "+cya", "+replace", "+sprengfalle", "+ecstalker", "+eristcool",
 "+gamerule", "+fakegrief", "+mass", "+firestalker", "+credits", "+serverisunderattack", "+rakete", "+ridedragon",
 "+plugin", "+mega", "+kill", "+loopkill", "+griefer", "+pt", "+passwort", "+whitelist", "+scann", "+fakescann",
 "+attack", "+pserver", "+server", "+pos1", "+pos2", "+set", "+cube", "+info", "+invsee", "+clearchat", "+tp",
 "+protection", "+nuker", "+map"]
 blacklisted-classpath: "me/jan"
TheSieuToc:
 checkType: MALWARE
 blacklisted-authors: "Juno"
 blacklisted-strings: "I_Can_Hack"
 blacklisted-classpath: "xyz.juno.thesieutoc"
Timber:
 checkType: MALWARE
 blacklisted-authors: ["Wordsmithy", "aurilisdev"]
 blacklisted-checksum: ["6BA06936CB33FA3CFF5F923D49BB860F81B4C367", "3D027885868B5C8C2F1C6A188DFF62023C3AC1E2"]
Timber2:
 checkType: MALWARE
 blacklisted-authors: "BlackFlag"
 blacklisted-strings: "http://www.blackflagtv.de"
 blacklisted-classpath: "de/blackflag"
Trading:
 checkType: MALWARE
 blacklisted-strings: "plugins/PluginMetrics.jar"
 blacklisted-classpath: "net/spectralcraft/dev"
TestPluginFirst:
 checkType: PUP
 blacklisted-strings: "waddupniggers"
 blacklisted-classpath: "me/itzpepi"
WebsiteUpdater:
 checkType: MALWARE
 blacklisted-author: "BlackFlag"
 blacklisted-strings: "http://www.blackflagtv.de"
 blacklisted-classpath: "de/blackflag"
NickSystem:
 checkType: MALWARE
 blacklisted-checksum: "A37DABD50E2D595EC8A554DA39A6A27E2EDC399C"